{{- if .Values.configmap.enabled }}
apiVersion: v1
data:
  pass: dWtnYnM=
kind: Secret
metadata:
  name: user-secret
{{ range .Values.tenants }}
  namespace: {{ .namespace }}
{{ end }}
type: Opaque
{{- end }}
