{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-policy-cm
{{ range .Values.tenants }}
  namespace: {{ .namespace }}
{{ end }}
data:
  job.sh: |-
{{ include (print $.Template.BasePath "/_helper_create_bucket_userpolicy.txt") . | indent 4 }}
{{- end }}
